## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
boston = datasets.load_boston()

In [3]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [4]:
boston.data[:].shape

(506, 13)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# Linear Regression

In [6]:
lr = linear_model.LinearRegression()
lr.fit(x_train, y_train)
lr_y_pred = lr.predict(x_test)

In [7]:
lr.coef_

array([-1.14743504e-01,  4.70875035e-02,  8.70282354e-03,  3.23818824e+00,
       -1.67240567e+01,  3.87662996e+00, -1.08218769e-02, -1.54144627e+00,
        2.92604151e-01, -1.33989537e-02, -9.07306805e-01,  8.91271054e-03,
       -4.58747039e-01])

In [8]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, lr_y_pred))

Mean squared error: 25.41


# Lasso

In [9]:
lasso = linear_model.Lasso(alpha=1.0)
lasso.fit(x_train, y_train)
lasso_y_pred = lasso.predict(x_test)

In [10]:
lasso.coef_

array([-0.06479441,  0.04581271, -0.        ,  0.        , -0.        ,
        1.17737271,  0.011112  , -0.73717556,  0.23337442, -0.01550582,
       -0.69307422,  0.00769147, -0.69322155])

In [11]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, lasso_y_pred))

Mean squared error: 28.95


# Rdge

In [12]:
ridge = linear_model.Ridge(alpha=1.0)
ridge.fit(x_train, y_train)
ridge_y_pred = ridge.predict(x_test)

In [13]:
ridge.coef_

array([-1.11085562e-01,  4.79127892e-02, -2.36686153e-02,  2.96582333e+00,
       -9.35915972e+00,  3.92379527e+00, -1.73228057e-02, -1.43323726e+00,
        2.74489395e-01, -1.38858412e-02, -8.31911824e-01,  9.25837299e-03,
       -4.67523596e-01])

In [14]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, ridge_y_pred))

Mean squared error: 25.73
